version: '3.8'

services:
  service1:
    build: ./service1
    ports:
      - "3000:3000"
    volumes:
      - ./service1/cache:/app/cache

  service2:
    build: ./service2
    ports:
      - "4000:4000"
    depends_on:
      - service1